apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxcopier
  labels:
    app: fxcopier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fxcopier
  template:
    metadata:
      labels:
        app: fxcopier
    spec:
      containers:
      - name: fxcopier
        image: lokispundit/fxcopier:latest
        volumeMounts:
        - mountPath: /mnt/data
          name: restoredata
        - mountPath: /mnt/frozen_buckets
          name: frozenbuckets
        - mountPath: /opt/fishstix
          name: fishstix
      volumes:
        - name: restoredata
          hostPath:
            path: /mnt/data
            type: Directory
        - name: frozenbuckets
          hostPath:
            path: /mnt/frozen_buckets
            type: Directory
        - name: fishstix
          hostPath:
            path: /opt/fishstix
            type: Directory
