apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofishing
  labels:
    app: gofishing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gofishing
  template:
    metadata:
      labels:
        app: gofishing
    spec:
      containers:
      - name: gofishing
        image: lokispundit/gofishing
        volumeMounts:
        - mountPath: /mnt/data
          name: restoredata
        - mountPath: /mnt/nfs
          name: nfs
        - mountPath: /mnt/sshfs
          name: sshfs
      volumes:
        - name: restoredata
          hostPath:
            path: /mnt/data
            type: Directory
        - name: nfs
          hostPath:
            path: /mnt/nfs
            type: Directory
        - name: sshfs
          hostPath:
            path: /mnt/sshfs
            type: Directory
